language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
notifications:
  slack: comp3001:v2KOKh1ja8a3kV8N7SrdFP7d
install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - grunt build
  - npm install -g web-component-tester
  - set -o pipefail
script:
  - wct --plugins sauce | cat
before_deploy:
  - npm install -g firebase-tools
  - chmod +x configs/deploy.sh
deploy:
  - provider: script
    script: configs/deploy.sh
    skip_cleanup: true
    on:
      branch: master
