language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - grunt build
  - npm install -g web-component-tester
  - set -o pipefail
script:
  - wct --plugins sauce | cat
